# -*- coding: utf-8 -*-
"""financeiro - previsao de custos de franquia

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v3DC50VfKdWw58-ALdRH-ckBCWIproUB
"""

import pandas as pd
from io import StringIO
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

# String que contém os dados
dados_franquia_str = """
ID,Area_m2,Populacao_Local,Taxa_Franquia_Base,Nivel_Risco_Cid,Custo_Total
1,80,150,50.0,2,180
2,120,500,65.0,4,250
3,50,50,40.0,1,120
4,150,800,70.0,5,320
5,100,200,55.0,3,200
6,70,100,45.0,2,150
7,130,650,68.0,4,280
8,60,30,35.0,1,110
9,90,300,60.0,3,220
10,110,400,62.0,4,240
"""

# Cria o DataFrame
df_franquia = pd.read_csv(StringIO(dados_franquia_str))

# Define Features (X) e Target (y)
X = df_franquia.drop(['ID', 'Custo_Total'], axis=1)
y = df_franquia['Custo_Total'] # Target em Milhares de Reais

# Treinamento (usaremos todo o conjunto como treino inicial)
X_train = X
y_train = y

# Instancia e treina o modelo de Regressão Linear
model_custo = LinearRegression()
model_custo.fit(X_train, y_train)

print("--- DataFrame de Custos de Franquia Criado ---")
print(df_franquia.head())
print("\nTreinamento do Modelo de Custos concluído.")

# Faz a previsão
y_pred = model_custo.predict(X_train)

# Avalia as métricas
mse = mean_squared_error(y_train, y_pred)
r2 = r2_score(y_train, y_pred)
rmse = np.sqrt(mse)

print("\n--- Resultados da Avaliação (Regressão Linear) ---")
print(f"Erro Quadrático Médio (MSE): {mse:.4f}")
print(f"Raiz do Erro Quadrático Médio (RMSE): {rmse:.4f}")
print(f"R-Quadrado (R²): {r2:.4f}")

# Explicabilidade: Coeficientes
coeficientes = pd.Series(model_custo.coef_, index=X.columns)
intercepto = model_custo.intercept_

print("\n--- Coeficientes do Modelo (Pesos dos Custos) ---")
print(f"Intercepto (Custo Base Fixo): {intercepto:.2f} Mil R$")
print("--- Peso de Cada Feature (Variação no Custo) ---")
print(coeficientes.sort_values(ascending=False))